### ISSUE TITLE
Incorrect display of shorthand empty tags in the editor

### ISSUE THREAD

**Issue by iafan** [evernote/zing#105]
Consider the following unit:

https://translate.evernote.com/kab/windows_v6_evernote/translate/entray/MsgBoxes.xml.po#unit=6265658

In the database, we have the following string:
`Could not add tray icon, error: <Error />.`

But in the editor UI it displayed like this:
`Could not add tray icon, error: <Error ></Error>.`

Because of that, translators use the same expanded `<Error ></Error>` form in the translation and get checks triggered. I believe this is a regression, as we use used to translate these strings in the past just fine.

**Comment by iafan** [comment]
This is what happens:

1.  We get the editor row as HTML. This HTML contains a `<script>....</script>` tag that initializes the editor.
2. We render this HTML in a container using jQuery `html()` method.
3. In `html()` method, jQuery explicitly tests if the passed HTML string contains certain tags, like `<script>`, `<style>`, or `<link>`. If any of these are found, it uses `this.empty().append( value );` logic instead of native `elem.innerHTML = value;`.
4. `jQuery.append()` internally calls `jQuery.buildFragment()` from the given HTML string, and this is where ([likely in this code](https://github.com/evernote/zing/blob/master/pootle/static/js/vendor/jquery/jquery.js#L5785-L5788)) the resulting string inside embedded JS code gets rewritten (`<Error />` is replaced with `<Error ></Error>`).

The code accidentally worked in the past because the `to_js` template filter would do double escaping and then pass through a runtime `JSON.parse()` call. Now that we don't do this kind of escaping, we need to deal with this specific case.

The ultimate fix would be to get rid of this whole HTML editor row snippet and script inside this snippet (by e.g. using a proper React component). meanwhile, a short-term workaround can probably be to make sure the rendered JavaScript strings inside editor row initialization code don't match [this regular expression](https://github.com/evernote/zing/blob/master/pootle/static/js/vendor/jquery/jquery.js#L5413).

I'll PR a change for this fix shortly.

**Comment by julen** [comment]
Verified on my side, GTM 👍.
