### ISSUE TITLE
Display disabled project contents in the browser

### ISSUE THREAD

**Issue by iafan** [evernote/zing#122]
It seems that with the browser view refactoring we no longer display disabled project's contents to the admin. The data is being provided on the page, but the React component doesn't render the rows.

**Comment by julen** [comment]
It's unclear whether you are referring to browsing contents of disabled projects or listing the languages of disabled projects.

FWIW the disabled project contents are available to admins and can be browsed. The list of languages in disabled projects, on the other hand, hides disabled children items _by design_ (which happen to be all languages in this particular case), and it's no different from the previous implementation.

In this regards, it would be more intuitive initializing the table with the _Show disabled_ toggle turned on for disabled projects.

**Comment by iafan** [comment]
Previously, when we would display disabled items by default, the UX made sense: you could go as an admin  to a disabled project, see all the items and browse them. Now that we hide disabled items by default, all you see is a blank table header.

I believe there are two issues here:

1) **(Main one)** Translation projects are not actually _disabled_ inside a disabled project. It is the project that is disabled as a whole, but otherwise translation projects and stores have corresponding files on the disk. I, as an admin, would like to preview the disabled project the same way as it would be visible to other users once the project is opened. So I guess we're missing the ability to distinguish really disabled (obsolete) tp/folders/files and the ones that are simply not visible to non-admins. It can be something that we accidentally broke while reimplementing the table as a React component.

2) **(Secondary one)** When there are only disabled rows in the table, it makes sense either to auto-show disabled items instead of showing an empty header.

**Comment by julen** [comment]
To the extent of my knowledge, this issue was already fixed and doesn't apply anymore. Feel free to reopen if not.
