### ISSUE TITLE
When opening a link for a now missing unit, the wheel keeps spinning

### ISSUE THREAD

**Issue by iafan** [evernote/zing#166]
When one follows some link to a unit which is no longer available ([example](https://translate.evernote.com/ja/kb2_evernote/translate/articles/208314748.xml.po#unit=6317072)), the UI doesn't update properly: the wheel keeps spinning, and there's no 'Unit not found' message.

**Comment by julen** [comment]
The situation is somehow handled [in the `goto` method](https://github.com/evernote/zing/blob/db103148f9bc0e534f28990ad23c57b4912e0898/pootle/static/js/editor/UnitList.js#L106-L108) but callsites take no action upon (there are only 3 callers, two of them in the routing code, the other one as part of the click handler for view rows).

By the way, I am unsure what your suggestion is, as there is no _Unit not found_ message anywhere; are you referring to the _No units found_ message perhaps? However that is used when there are no results at all (plus it displays no rows), and in this context it would be misleading.

**Comment by iafan** [comment]
My suggestion was to show some meaningful message when the unit is not found, and make sure user understands that the unit wasn't found in the first place (previously, IIRC, we would just silently show the first available unit instead, not the one the user explicitly wanted to see when following some permalink, which was also bad). Sorry if my description was a bit ambiguous. I was referring to a 'Unit not found' message as something we would want to have implemented.

I refactored the related code and messaging a bit, and this is how it will look like now:

1. When there are no units in current language/section/folder/file, the user will see the following message:
```
No units found in this translation scope.
```

This message is supposed to be visible to admins only, since currently only admins can see empty items in the browser.

2. When no units match the search criteria, the message will be:
```
No units match your search criteria.
```

3. When there are units in current language/section/folder/file, but the requested unit wasn't found in the list, the message will be:
```
Unit #NNNNNNNN is no longer available.
_Show all other units in this translation scope_
```
Clicking on a link will show all the units (we will go to the first found unit).

4. When there are units matching search criteria, but the requested unit wasn't found in the list, the message will be:
```
Unit #NNNNNNNN no longer matches your search criteria or is no longer available.
_Show all other units matching your search criteria_
```
Clicking on a link will show all the units (we will go to the first found unit).

I'll make a PR soon.
