### ISSUE TITLE
`update_stores` fails to resurrect unsynced obsolete units

### ISSUE THREAD

**Issue by julen** [evernote/zing#246]
There is a synchronization bug where:

1. Unit `U` is translated (or somehow changed) in store `X`, and it is still NOT synced to disk
2. The file for store `X` ceases to exist on disk
3. `update_stores` is run, making all units in store `X` obsolete
4. The file for store `X` is brought back to the previous location on disk
5. `update_stores` is run, and units from the file are resurrected, except those which contain unsynced changes such as unit `U`.

**Comment by julen** [comment]
So in this example unit `U` needs to be resurrected, and we discussed two different ways to approach this:

1. In the `UnitUpdater.update_unit()` logic, consider `U` as not causing conflicts. In other words, this would treat `U` as a previously non-existing unit, which means that the contents of unit `U` from the file will be used, discarding the changes that might have happened since the last sync. Anyone can still access the previous translation (which wasn't sync'ed) in the timeline.

2. Do not change any conflict semantics, and obsolete units that changed since the last sync should be restored right away, thus keeping their last changes which haven't been synchronized yet. This also means that since there is a conflict, the expected resolution will happen: the `U` unit's translation from the file will be made available as a suggestion.

**Comment by iafan** [comment]
Let's go with #2. As we discussed before, we need to pay extra attention to unit change_id's so that any restored and yet unsynchronized translations would be propagated to files on subsequent `sync_stores` run.
