### ISSUE TITLE
Fresh installation of Zing not working

### ISSUE THREAD

**Issue by RobinCsl** [evernote/zing#289]
Hi there,

I have tried to install Zing for the last few hours and cannot seem to seamlessly install Zing and have it working. I will describe what I have done so that you could reproduce it.
I religiously followed all the steps described in [here](https://github.com/evernote/zing/blob/master/docs/server/installation.rst#id4). Once I run 
```bash (env) $ zing runserver --insecure```
the server starts correctly. However, once I access the URL in my browser, I get the following error:
```bash
(env) $ zing runserver --insecure
Performing system checks...

System check identified some issues:

WARNINGS:
?: (pootle.W004) Email server is not available.
	HINT: Review your email settings and make sure your email server is working.
?: (pootle.W006) The sqlite database backend is unsupported
	HINT: Set your default database engine to postgresql or mysql
?: (pootle.W010) DEFAULT_FROM_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: DEFAULT_FROM_EMAIL is used in all outgoing Pootle email.
Don't forget to review your mail server settings.
?: (pootle.W011) POOTLE_CONTACT_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: POOTLE_CONTACT_EMAIL is the address that will receive messages sent by the contact form.

System check identified 4 issues (0 silenced).
December 21, 2017 - 12:46:59
Django version 1.11.8, using settings 'pootle.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):

 [...]

  File "/home/robin/dev/newest_zing/env/local/lib/python2.7/site-packages/webassets/bundle.py", line 334, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7f5a5d71e810>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/zing-icons.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
[2017-12-21T12:47:04]	"GET / HTTP/1.1" 500 59
2017-12-21 12:47:04,103 ERROR "GET / HTTP/1.1" 500 59
```

After some googling, I found that the same error happened for some Pootle installations, and it seems related to the fact that the assets are not built. [http://docs.translatehouse.org/projects/pootle/en/latest/developers/customization.html#customization](http://docs.translatehouse.org/projects/pootle/en/latest/developers/customization.html#customization)

So I executed: 
```bash
(env) $ zing webpack
```
which returned the following error:
```bash
CommandError: webpack executable not found.
Make sure to install it by running `cd /home/robin/dev/newest_zing/env/local/lib/python2.7/site-packages/pootle/static/js && npm install`
```

so I executed the command:
```
cd /home/robin/dev/newest_zing/env/local/lib/python2.7/site-packages/pootle/static/js && npm install
```
and finally,
```
(env) $ cd -
(env) $ zing webpack
(env) $ zing collectstatic --noinput --clear -i node_modules
(env) $ zing assets build
```

After all this is done, I managed to run the server by doing 
``` (env) $ zing runserver --insecure ```
which started the server correctly and once I access [localhost:8000](localhost:8000), I get the following view with the following errors in the console

![zing-error](https://user-images.githubusercontent.com/22741774/34256909-d2c1254c-e657-11e7-84d5-dd3b9ee502d5.png)
and if I tried to click on __Sign in__, I would get this other error:
```
Uncaught ReferenceError: gettext is not defined
    at t.getScreen (http://localhost:8000/assets/js/common/app.min.ed8b2ec8.js:1:227825)
    at t.render (http://localhost:8000/assets/js/common/app.min.ed8b2ec8.js:1:228654)
    at l._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8000/assets/js/vendor.min.efc4ede4.js:1:195026)
    at l._renderValidatedComponent (http://localhost:8000/assets/js/vendor.min.efc4ede4.js:1:195114)
    at l.mountComponent (http://localhost:8000/assets/js/vendor.min.efc4ede4.js:1:191388)
    at Object.mountComponent (http://localhost:8000/assets/js/vendor.min.efc4ede4.js:1:131002)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8598:20)
    at l.mountComponent (http://localhost:8000/assets/js/vendor.min.efc4ede4.js:1:191484)
    at Object.mountComponent (http://localhost:8000/assets/js/vendor.min.efc4ede4.js:1:131002)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8598:20)
getScreen @ app.min.ed8b2ec8.js:1
render @ app.min.ed8b2ec8.js:1
_renderValidatedComponentWithoutOwnerOrContext @ vendor.min.efc4ede4.js:1
_renderValidatedComponent @ vendor.min.efc4ede4.js:1
mountComponent @ vendor.min.efc4ede4.js:1
mountComponent @ vendor.min.efc4ede4.js:1
obj.(anonymous function) @ backend.js:8598
mountComponent @ vendor.min.efc4ede4.js:1
mountComponent @ vendor.min.efc4ede4.js:1
obj.(anonymous function) @ backend.js:8598
mountComponent @ vendor.min.efc4ede4.js:1
mountComponent @ vendor.min.efc4ede4.js:1
obj.(anonymous function) @ backend.js:8598
mountComponent @ vendor.min.efc4ede4.js:1
mountComponent @ vendor.min.efc4ede4.js:1
obj.(anonymous function) @ backend.js:8598
u @ vendor.min.efc4ede4.js:1
perform @ vendor.min.efc4ede4.js:1
l @ vendor.min.efc4ede4.js:1
perform @ vendor.min.efc4ede4.js:1
batchedUpdates @ vendor.min.efc4ede4.js:1
batchedUpdates @ vendor.min.efc4ede4.js:1
_renderNewRootComponent @ vendor.min.efc4ede4.js:1
obj.(anonymous function) @ backend.js:8588
_renderSubtreeIntoContainer @ vendor.min.efc4ede4.js:1
render @ vendor.min.efc4ede4.js:1
open @ app.min.ed8b2ec8.js:1
on.t @ app.min.ed8b2ec8.js:1
dispatch @ vendor.min.efc4ede4.js:1
v.handle @ vendor.min.efc4ede4.js:1
```

I am a bit at a loss as to what to do next. I use Ubuntu 16.04 in case that's useful. 

Looking forward to hearing from you!

Best wishes

**Comment by iafan** [comment]
Thanks for writing this up! It looks to me like assets were not generated properly. Try running a `make assets` command in Zing directory (where Makefile is) and see if runs correctly, then start the server again.

If that doesn't help, let's hear from @julen who'll be back from the vacation in January.

**Comment by RobinCsl** [comment]
I tried running `zing assets build` again, to no avail. I edited my previous post as I misformatted the end slightly. You can now see the screenshot I have at the moment. 
I could not locate a Makefile in Zing directory, or rather I could locate many, most of which were located in node_modules folder in `zing/env/lib/python2.7/site-packages/pootle/assets/js`.
![makefilesinzing](https://user-images.githubusercontent.com/22741774/34513850-9ec87552-f06a-11e7-990f-a0fdb8293601.png)

Thank you for your answer!

**Comment by iafan** [comment]
The Makefile in question is the one in the root folder of the project: https://github.com/evernote/zing/blob/master/Makefile

As you can see, `make assets` does a little bit more than `zing assets build`: https://github.com/evernote/zing/blob/master/Makefile#L24-L37

**Comment by RobinCsl** [comment]
I see. Since I did
```pip install https://github.com/evernote/zing/archive/master.zip
```
I never saw that folder and Makefile. Cloning the repo, I could run `make assets` and got the following error: 
```
[zing][master]$ make assets
npm --version
5.5.1
node --version
v9.2.0
cd /home/robin/Documents/new_zing/zing/pootle/static/js && \
npm install && \
cd /home/robin/Documents/new_zing/zing

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/robin/Documents/new_zing/zing/pootle/static/js/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN zing@0.6.0 No description

added 734 packages in 32.803s
python manage.py compilejsi18n
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    cmd_log(*sys.argv)
  File "/home/robin/Documents/new_zing/zing/pootle/core/log.py", line 61, in cmd_log
    fn = settings.LOGGING.get('handlers').get('log_action').get('filename')
  File "/home/robin/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/robin/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/robin/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 116, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Makefile:25: recipe for target 'assets' failed
make: *** [assets] Error 1
```
But I assume this is not enough anyway to run the server from the cloned repo. Would you mind guiding me through this?

**Comment by iafan** [comment]
The error suggests you need to set your own SECRET_KEY in the Zing config.

You probably need to make a copy of [settings/90-dev-local.conf.sample](https://github.com/evernote/zing/blob/1e3f55802748136d7f1df4ccfb4c0dae686ba100/pootle/settings/90-dev-local.conf.sample) file (copy it to `settings/90-dev-local.conf`), then try `make assets` again.

This is somewhat described in https://github.com/evernote/zing/blob/605b1aeedd95c576391fd079b03fc00b580e453b/docs/developers/hacking.rst

**Comment by RobinCsl** [comment]
It seems to be working fine now. 

There is nothing in the default projects `Terminology` and `Tutorial` though. 

It might be necessary to update the installation guidelines since the current one does not ask to clone the repo and follow the _hacking_ way. By the way, the `hacking.rst` file would need to indicate that ZING_SETTINGS must be exported after copying `90-dev-local.conf.sample` to `90-dev-local.conf`. 

I will now try to hook it up with Serge. Thank you!

**Comment by julen** [comment]
Hi @RobinCsl, I'm sorry to hear you had to go through some trouble and apologies for the late reply (on vacation till next week.)

The docs in general need to be reworked, and we have [a warning in place not to rely on them](https://github.com/evernote/zing/blob/master/docs/README.md) but it looks like it can easily go unnoticed. Please let us know if you have any ideas to make the warning more prominent for the time being.

The hacking docs are more up-to-date and reliable than the installation docs — I updated those recently based on some questions from another user on gitter.

The default projects being empty very likely indicates that your translation directory contains no files. Unless you customized the translation directory location, that should work by default though.

**Comment by julen** [comment]
The docs were reworked some time ago already and the installation steps have been fixed too.
