### ISSUE TITLE
Support Plurr preview for simple {FOO}-style placeholders

### ISSUE THREAD

**Issue by iafan** [evernote/zing#468]
Right now we look for `{FOO:<...>}` style placeholders in the string to determine whether we need to show the live Plurr preview panel. However, we could expand that to any strings that contain simple placeholders like `{FOO}` as well, since these are also valid in Plurr (and Plurr can be used to render such strings even if they don't contain plurals or choices).

Example of such a string:

![Screen Shot 2020-04-24 at 12 57 59](https://user-images.githubusercontent.com/1728158/80251919-422a3700-862b-11ea-94c7-958951668eed.png)

**Comment by benjamimo1** [comment]
Since this ticket is similar to the Emoji Highlight ticket I'll take a look

**Comment by benjamimo1** [comment]
Do you have an example (unit) of a live Plurr preview panel?

**Comment by iafan** [comment]
@benjamimo1 here you go: https://translate.evernote.com/ru/android_evernote/translate/strings.xml.po#unit=6140694

You can find such units in Zing by searching for `_PLURAL`.

**Comment by benjamimo1** [comment]
Relevant path: /pootle/static/js/editor/components/plurr/PlurrPreview.js

**Comment by benjamimo1** [comment]
@iafan can you reference a code line where "Right now we look for {FOO:<...>} " happens?

**Comment by iafan** [comment]
@benjamimo1 I'd start here: https://github.com/evernote/zing/blob/2d130c029affe82a5918e539fcbc1913bf8c9b7f/pootle/static/js/editor/containers/EditorContainer.js#L73

**Comment by benjamimo1** [comment]
Current status:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/26126311/81598019-a28fd700-9394-11ea-913f-ff4b4692b86b.png">
