### ISSUE TITLE
Incorrect number with the word count tracker

### ISSUE THREAD

**Issue by benjamimo1** [evernote/zing#481]
The word counter which can be found in the upper right corner of the screen and it is not updating correctly.
The number of added words to a unit is not a perfect match to the increase in the word count tracker.
Steps to reproduce:
- Select a unit
- Add words to the unit
- Click submit
The increase in the word counter should match the number of added words but it does not.
https://drive.google.com/file/d/1Vd0l4lVDoOLR7EMiA2R5Uu5wjVMHUkOq/view?usp=sharing

**Comment by iafan** [comment]
@benjamimo1 this is not a word counter, though. This is score, which is calculated differently depending on the "value" of actions that a user performs (e.g. translation, review, suggestion review).

**Comment by benjamimo1** [comment]
@iafan Thanks for the input! We'll discuss closing this ticket in favor of one which makes it easier for translators to understand what the score means.

**Comment by iafan** [comment]
FYI: we have this info here: https://translate.evernote.com/pages/help/score/
