### ISSUE TITLE
UI hangs indefinitely when attempt to translate a .po file with <= 10 entries

### ISSUE THREAD

**Issue by li-dl** [evernote/zing#484]
Steps to reproduce:
1) Use `manage.py update_stores --overwrite --force` to upload a .po file with 10 entries.
2) In the web UI, browse to that specific file and click **Continue translation**.
3) A spinner appears and never finishes spinning.

If a .po file with 11 or more entries is uploaded at step 1, it works correctly - the list of translations is shown.

Testing Zing v0.9.4.

In Firefox 78.0.2, the console shows this at step 3:
```
Uncaught TypeError: this.unit is undefined
    goto     http://172.18.74.142/assets/js/editor/app.min.880e948d.js:1
    then     http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    u        http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    fireWith http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    u        http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    u        http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    fireWith http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    then     http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    u        http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    fireWith http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    C        http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
    t        http://172.18.74.142/assets/js/vendors/app.min.5822099a.js:25
```

In Edge 83.0.478.61, the console shows this at step 3:
```
Uncaught TypeError: Cannot read property 'provideFullData' of undefined
    at Array.<anonymous> (app.min.880e948d.js:1)
    at Array.<anonymous> (app.min.5822099a.js:25)
    at u (app.min.5822099a.js:25)
    at Object.fireWith [as resolveWith] (app.min.5822099a.js:25)
    at Object.<anonymous> (app.min.5822099a.js:25)
    at u (app.min.5822099a.js:25)
    at Object.fireWith [as resolveWith] (app.min.5822099a.js:25)
    at Object.<anonymous> (app.min.5822099a.js:25)
    at u (app.min.5822099a.js:25)
    at Object.fireWith [as resolveWith] (app.min.5822099a.js:25)
```

**Comment by li-dl** [comment]
![20200714-1047](https://user-images.githubusercontent.com/66452957/87368575-6ad62300-c5c1-11ea-9f22-d92ed1e33bf3.png)

**Comment by iafan** [comment]
Haven't experienced this one. Can you try e.g. https://translate.evernote.com/ru/comms_engine_evernote/workflows/ITI-ENA-NOT-PWL-88-2199-SecondDeviceUpsell/COMMENG-168/ and checking if you see an error there as well? This is just a random file that has 3 units (and 1 is marked is incomplete). I tested it on latest Chrome and Firefox, and didn't see any errors in the console or in the UI. What happens if you go back to the browsing mode on your instance? Do you have any console errors there as well?

**Comment by li-dl** [comment]
> Can you try e.g. https://translate.evernote.com/ru/comms_engine_evernote/workflows/ITI-ENA-NOT-PWL-88-2199-SecondDeviceUpsell/COMMENG-168/ and checking if you see an error there as well?

No errors in the console and the UI works correctly.

> What happens if you go back to the browsing mode on your instance? Do you have any console errors there as well?

No errors.

**Comment by iafan** [comment]
What database backend do you use, btw? Do you have at lease one worker running for stats calcultion? The fact that you see this error in different browsers suggests that this might be a server-side issue (i.e. Zing backend not returning the correct data). If nothing else helps, can you try installing the previous version of Zing (v0.9.3) and see if it makes any difference?

**Comment by li-dl** [comment]
> What database backend do you use, btw?

MySQL.

> Do you have at lease one worker running for stats calcultion?

Yes, `python manage.py rqworker &` was running, and `Admin -> Info -> Status` was showing `Running (2 workers)`.

However, I can't reproduce the bug today. Either with the original install or a completely new install.
Closing the issue until / unless I can find a way to reproduce it.
