### ISSUE TITLE
AutoIcon is prone to XSS

### ISSUE THREAD

**Issue by julen** [evernote/zing#55]
Steps to reproduce:
1. Set user account's full name to something like `</script>Name<script>alert('Hi')</script>`.
2. Open any page displaying `Avatar` components for this user, e.g. its profile page.
3. Hover over the avatar.

Observed behavior:
The script specified as a name is executed.

Expected behavior:
No script is run.

I believe this might be related to the tooltip (tipsy), but we will need to check.

**Comment by iafan** [comment]
Tipsy allows HTML in tooltips (and we use this feature in some places). So we just need to ensure we escape values we put into `title="..."` attribute, unless we know they contain safe HTML markup.
