### ISSUE TITLE
Use consistent naming for CSS classes

### ISSUE THREAD

**Issue by julen** [evernote/zing#57]
Some recently-added components started using the `FooBarBaz` style for CSS class names, whereas we have always been using `foo-bar-baz`. Let's stick to the latter for consistency and switch the new ones to the traditional style.

**Comment by iafan** [comment]
When introducing this, my reason here was that we want to make sure what parts of the CSS belong to components (and only use this style for the root component class). This way it's easy to see that all rules that start with `.BrowserTable` relate to `BrowserTable` React component. As compared to that, `.browser-table` is less descriptive and can clash wit other ad-hoc styles that we already have accumulated. This naming would also allow us to cleanly migrate all the styles that belong to the components under their unique namespaces as we move parts of the UI into React, and at any time to see what global 'unclaimed' CSS styles we still have.

If you feel this approach is not worth the benefits, or if you have a better solution to dealing with CSS legacy, please speak up. Probably moving to another way of dealing with CSS will render such class names irrelevant.

Renaming these style names to `foo-bar-baz` ones is pretty straightforward, but I just wanted to emphasize that it was a deliberate decision that I believe would help us unwind the current CSS files.

**Comment by julen** [comment]
> Probably moving to another way of dealing with CSS will render such class names irrelevant.

Exactly, and since we already have #9 on file and we are willing to have it addressed sooner than later, I really don't see the need to introduce and mix new naming conventions, especially seeing that these styles are already living in separate component-specific CSS files.

Moving declarations to separate files should be a good enough starting point to unwind the current monolithic CSS rules; the rest will depend upon the solution we decide on for components' styling.
